# IMPORTANTE: No modificar ni borrar ni renombrar este archivo

all: a.out
	./a.out
	
a.out:
	g++ -std=c++11 test_hw1.cpp

apariciones: a.out
	./a.out apariciones
	
mayor: a.out
	./a.out mayor

reverso: a.out
	./a.out reverso

ordenado: a.out
	./a.out ordenado

clean:
	rm a.out
