# IMPORTANTE: No modificar ni borrar ni renombrar este archivo

all: a.out
	./a.out
	
a.out:
	gcc test_hw4.c -o a.out

sin_cargar: a.out
	./a.out s

maximos_inscriptos: a.out
	./a.out m

promedio_umbral: a.out
	./a.out u

clean:
	rm a.out